#!/bin/sh -uxe
export DESTDIR="$1"

cmake -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_INSTALL_LIBDIR=lib \
    -D AVIF_BUILD_APPS=ON \
    -D AVIF_CODEC_AOM=ON \
    -D AVIF_CODEC_DAV1D=ON \
    -D AVIF_CODEC_RAV1E=ON \
    -D AVIF_CODEC_SVT=ON \
    -D AVIF_BUILD_GDK_PIXBUF=ON

ninja -C build
ninja -C build install
