#!/bin/sh -uxe

./configure \
	--prefix=/usr \
	--disable-static \
	--enable-hashes=strong,glibc \
	--enable-obsolete-api=no \
	--disable-failure-tokens \
    --disable-werror

make
make DESTDIR="$1" install
