#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    -D spectre=disabled \
    -D tee=enabled \
    -D tests=disabled \
    -D symbol-lookup=disabled \
    -D gtk_doc=true \
    ${MESON_OPTIONS/-D b_lto=true/}

ninja -C build
ninja -C build install
