#!/bin/sh -uxe

autoreconf -fiv

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib/vde2 \
    --enable-experimental

make V=1 
make DESTDIR="$1" install 
