#!/bin/sh -uxe

# Fix gccgo breaking in go bootstrap.
# See github.com/golang/go/issues/47771 for details.
#patch -d gcc -p1 -i ../7edb992d8195572e2c823fedab319eb6cb2f0f32.patch

# Do not run fixinclude
sed -i "s|\./fixinc\.sh|-c true|" gcc/gcc/Makefile.in

# Use lib not lib64 by default
sed -i '/m64=/s/lib64/lib/' gcc/gcc/config/i386/t-linux64
sed -i 's/lib64/lib/' gcc/gcc/config/i386/linux64.h

unset CC
unset CXX
unset CPP
unset LD

export CFLAGS="-march=native -mtune=native -O3 -fgraphite -floop-nest-optimize"
unset CPPFLAGS
export CXXFLAGS="$CFLAGS"
unset LDFLAGS

mkdir -p build
cd build

export libat_cv_have_ifunc=yes
../gcc/configure \
    --prefix=/usr \
    --libexecdir=/usr/libexec \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --with-bugurl=https://github.com/mdartmann/mkiss/issues \
    --with-linker-hash-style=gnu \
    --with-system-zlib \
    --enable-__cxa-atexit \
    --enable-cet=auto \
    --enable-ehcking=release \
    --enable-clocale=gnu \
    --enable-default-pie \
    --enable-default-ssp \
    --enable-gnu-indirect-function \
    --enable-gnu-unique-object \
    --enable-linker-build-id \
    --enable-lto \
    --enable-shared \
    --enable-threads=posix \
    --disable-libssp \
    --disable-libstdcxx-pch \
    --disable-werror \
    --disable-multilib \
    --with-build-config=bootstrap-lto \
    --enable-link-serialization=1 \
    --enable-languages=c,c++,fortran,go,lto,objc,obj-c++

make
make DESTDIR="$1" install

# Add LTO
install -vdm755 "$1/usr/lib/bfd/plugins"
ln -sfv ../../libexec/gcc/$(cc -dumpmachine)/$2/liblto_plugin.so \
	"$1/usr/lib/bfd/plugins/liblto_plugins.so"

ln -s gcc "$1/usr/bin/cc"
install -Dm755 ../c99 "$1/usr/bin/c99"

python -m compileall "$1"/usr/share/gcc-$2 
python -O -m compileall "$1"/usr/share/gcc-$2 
