#!/bin/sh -uxe


# Use lib not lib64 by default
sed -i '/m64=/s/lib64/lib/' gcc/gcc/config/i386/t-linux64
sed -i 's/lib64/lib/' gcc/gcc/config/i386/linux64.h

unset CC
unset CXX
unset CPP
unset LD

export CFLAGS="-march=native -mtune=native -O3 -fgraphite -floop-nest-optimize"
unset CPPFLAGS
export CXXFLAGS="$CFLAGS"
unset LDFLAGS

mkdir -p build
cd build

export libat_cv_have_ifunc=yes
../gcc/configure \
    --prefix=/usr \
    --libexecdir=/usr/libexec \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --with-bugurl=https://github.com/mdartmann/mkiss/issues \
    --disable-multilib \
    --enable-symvers \
    --disable-libmpx \
    --disable-libmudflap \
    --enable-libsanitizer \
    --disable-werror \
    --enable-nls \
    --enable-install-libiberty \
    --enable-__cxa_atexit \
    --enable-default-pie \
    --enable-default-pic \
    --enable-default-ssp \
    --enable-shared \
    --enable-threads \
    --enable-graphite \
    --enable-plugin \
    --enable-lto \
    --enable-tls \
    --with-isl \
    --enable-languages=c,c++,lto,objc,obj-c++,go \
    --without-included-gettext \
    --with-system-zlib \
    --with-gmp=/usr \
    --with-mpc=/usr \
    --with-mpfr=/usr \
    --enable-threads=posix \
    --enable-checking=release \
    --with-linker-hash-style=gnu \
    --enable-gnu-indirect-function \
    --enable-linker-build-id \
    --enable-gnu-unique-object \
    --enable-clocale=gnu \
    --enable-cet=auto \
    --enable-bootstrap

make
make DESTDIR="$1" install

# Add LTO
install -vdm755 "$1/usr/lib/bfd/plugins"
ln -sfv ../../libexec/gcc/$(cc -dumpmachine)/$2/liblto_plugin.so \
	"$1/usr/lib/bfd/plugins/liblto_plugins.so"

ln -s gcc "$1/usr/bin/cc"
install -Dm755 ../c99 "$1/usr/bin/c99"
