#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    --prefix=/usr \
    --wrap-mode=nofallback \
    --buildtype=plain \
    -D tests=false \
    -D docs=false 

ninja -C build
ninja -C build install
