#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    --prefix=/usr \
    --buildtype=plain \
    -D examples="disabled" \
    -D server="enabled" \
    -D libseat-logind="systemd" \
    -D man-pages="enabled" 

ninja -C build
ninja -C build install
