#!/bin/sh -uxe

patch -p0 -i ca-dir.patch

./Configure \
	--prefix=/usr \
	--openssldir=/etc/ssl \
	--libdir=lib \
	shared \
	no-ssl3-method \
	enable-ec_nistp_64_gcc_128 \
	"-Wa,--noexecstack ${CFLAGS} ${LDFLAGS}" \
	linux-x86_64

make
make DESTDIR="$1" MANDIR=/usr/share/man MANSUFFIX=ssl install
