#!/bin/sh -uxe

./configure \
	--prefix=/usr \
	--localstatedir=/var \
	--bindir=/usr/bin \
	--sbindir=/usr/bin \
	--libdir=/usr/lib \
	--enable-usrdir-path \
	--enable-fs-paths-default=/usr/bin:/usr/local/bin \
	--enable-vipw \
	--enable-newgrp \
	--enable-chfn-chsh \
	--enable-write \
	--enable-mesg \
	--disable-more \
	--disable-makeinstall-chown \
	--with-systemd \
	--with-python=3

# Remove nonexsistant warnflag caused by configure.
find -name Makefile -exec sed -i 's|-Wembedded-directive||g' {} \;

make
make DESTDIR="$1" install

# Fix broken --sbindir.
mv -f "$1/usr/sbin/"* "$1/usr/bin"
rmdir "$1/usr/sbin"

install -Dm0644 "util-linux.sysusers" \
    "${1}/usr/lib/sysusers.d/util-linux.conf"

install -Dm0644 "60-rfkill.rules" \
    "${1}/usr/lib/udev/rules.d/60-rfkill.rules"

install -Dm0644 "rfkill-unblock_.service" \
    "${1}/usr/lib/systemd/system/rfkill-unblock@.service"
install -Dm0644 "rfkill-block_.service" \
    "${1}/usr/lib/systemd/system/rfkill-block@.service"

install -Dm0644 "pam-common" "${1}/etc/pam.d/chfn"
install -m0644 "pam-common" "${1}/etc/pam.d/chsh"
install -m0644 "pam-login" "${1}/etc/pam.d/login"
install -m0644 "pam-runuser" "${1}/etc/pam.d/runuser"
install -m0644 "pam-runuser" "${1}/etc/pam.d/runuser-l"
install -m0644 "pam-su" "${1}/etc/pam.d/su"
install -m0644 "pam-su" "${1}/etc/pam.d/su-l"
