#!/bin/sh -uxe

patch -Np1 -i responder.patch
rm responder.patch

install -Dm755 responder.sh "$1"/usr/bin/responder
rm responder.sh

install -d "$1"/usr/share/responder
install -d "$1"/var/log/responder
cp -ar * "$1"/usr/share/responder

