#!/bin/sh -uxe
export DESTDIR="$1"

cmake -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_CXX_FLAGS="$CXXFLAGS -fno-delete-null-pointer-checks"

ninja -C build
ninja -C build install
