#!/bin/sh -uxe

source /etc/kiss-flags/multilib.sh

NOCONFIGURE=1 ./autogen.sh

./configure \
    --prefix=/usr \
    --libdir=/usr/lib32

make
make DESTDIR="$1" install

rm -rf "$1"/usr/{include,bin}
