#!/bin/sh -uxe

source /etc/kiss-flags/multilib.sh

./configure \
    --prefix=/usr \
    --libdir=/usr/lib32 \
    --libexecdir=/usr/lib32 \
    --disable-static \
    --enable-hashes=strong,glibc \
    --enable-obsolete-api=no \
    --disable-failure-tokens \
    --disable-werror

make
make DESTDIR="$1" install

rm -rf "$1"/usr/{include,bin,share}
