#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
	${MESON_OPTIONS} \
	-D systemdsystemunitdir=/usr/lib/systemd/system \
	-D udevrulesdir=/usr/lib/udev/rules.d \
	-D sysconfdir=/usr/share

ninja -C build
ninja -C build install
