#!/bin/sh -uxe
export DESTDIR="$1"

cmake -B build \
    -D BIPR=0 \
    -D CMAKE_BUILD_TYPE=None \
    -D CMAKE_CXX_FLAGS="$CXXFLAGS" \
    -D CMAKE_C_FLAGS="$CFLAGS" \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_SKIP_RPATH=ON \
    -D LIBEXEC_INSTALL_DIR=/usr/lib \
    -D PERL_VENDORINSTALL=yes \
    -D WITH_WEBKIT3=OFF \
    -Wno-dev

cmake --build build
cmake --install build
