#!/bin/sh -uxe

sed -i "s|-w |-w -linkmode external |" Makefile

export CGO_CFLAGS="${CFLAGS}"
export CGO_LDFLAGS="${LDFLAGS}"
export CGO_CXXFLAGS="${CXXFLAGS}"
export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"

FZF_VERSION=${2} make

## Man page
install -Dm644 man/man1/fzf.1 "$1"/usr/share/man/man1/fzf.1
install -Dm644 man/man1/fzf-tmux.1 "$1"/usr/share/man/man1/fzf-tmux.1

## License
install -Dm644 LICENSE "$1"/usr/share/licenses/fzf/LICENSE

## Binaries
install -dm755 "$1"/usr/bin
install -m755 bin/fzf-tmux "$1"/usr/bin/
install -Dm755 target/fzf-linux_amd64 "$1"/usr/bin/fzf

## Completion and keybindings
install -dm755 "$1"/usr/share/fzf
install -m644 shell/*.bash shell/*.zsh "$1"/usr/share/fzf

## Vim plugin
install -Dm644 doc/fzf.txt "$1"/usr/share/vim/vimfiles/doc/fzf.txt
install -Dm644 plugin/fzf.vim "$1"/usr/share/vim/vimfiles/plugin/fzf.vim

