#!/bin/sh -uxe
export DESTDIR="$1"

sed -i "/installdir/s/'icons'/'pixmaps'/" panels/info-overview/meson.build

git submodule init
git submodule update 

meson build \
    ${MESON_OPTIONS/-D b_lto=true/}  

ninja -C build
ninja -C build install
