#!/bin/sh -uxe
export DESTDIR="$1"

export CFLAGS+=" -flto=auto -ffat-lto-objects"
export CXXFLAGS+=" -flto=auto -ffat-lto-objects"

meson build \
    ${MESON_OPTIONS} \
    -D gtk_doc=true \
    -D sysprof=disabled \
    -D autobahn=disabled \
    -D http2_tests=disabled \
    -D ntlm=disabled

ninja -C build
ninja -C build install
