#!/bin/sh -uxe
export DESTDIR="$1"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --libexecdir=/usr/lib/qemu \
    --smbd=/usr/bin/smbd \
    --enable-modules \
    --enable-sdl \
    --enable-slirp=system \
    --disable-werror

ninja -C build
ninja -C build  install

install -Dm644 65-kvm.rules "$1"/usr/lib/udev/rules.d/65-kvm.rules
install -Dm644 qemu-guest-agent.service -t "$1"/usr/lib/systemd/system
