#!/bin/sh -uxe


for i in *.patch; do
    patch -Np1 -i $i
done

sed -i "s|#include <curl/types.h||" src/flickcurl_internal.h

autoreconf -fiv

./configure \
    --prefix=/usr

sed -i "s| -shared | ${LDFLAGS}\0|g" libtool

make
make DESTDIR="$1" install
