#!/bin/sh -uxe

# fix issues with linker scripts
patch -Np1 -i *.patch

make ERRORS='' all

make DESTDIR="$1" libdir=/usr/lib bindir=/usr/bin mandir=/usr/share/man includedir=/usr/include \
       install	-j1 V=1
