#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    --buildtype=release \
    --prefix=/usr \
    -D documentation=false \
    ${MESON_OPTIONS/-D b_lto=true/}

ninja -C build
ninja -C build install
