#!/bin/sh -uxe
export DESTDIR="$1"

for i in *.patch; do
    patch -Np1 -i  $i
done

zsh
meson build \
    ${MESON_OPTIONS} \
    -D default_library=shared \
    -D gl_provider=osmesa

ninja -C build
ninja -C build install
