#!/bin/sh -uxe
export DESTDIR="$1"

git fetch

git cherry-pick -n \
    827494d6415b696a \
    effb1e09dee263cd

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D gtk_doc=true \
    -D doctool=disabled

ninja -C build
ninja -C build install

python -m compileall -d /usr/lib/gobject-introspection "$1/usr/lib/gobject-introspection"
python -O -m compileall -d /usr/lib/gobject-introspection "$1/usr/lib/gobject-introspection"
