#!/bin/sh -uxe
export DESTDIR="$1"

export CFLAGS+=" -fno-semantic-interposition"
export LDFLAGS+=" -Wl,-Bsymbolic-functions"

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D egl_device=true \
    -D wayland_eglstream=false \
    -D tests=false 

ninja -C build 
ninja -C build install
