#!/bin/sh -uxe

NOCONFIGURE=1 ./autogen.sh

./configure \
    --prefix=/usr \
    --disable-static \
    --enable-vala \
    --enable-gtk-doc

export CARGO_PROFILE_RELEASE_LTO=true CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1

sed -i "s| -shared | ${LDFLAGS}\0|g" libtool

make
make DESTDIR="$1" install
