#!/bin/sh -uxe

mkdir build && cd build

../configure \
    --prefix=/usr \
    --disable-nls \
    --enable-tui \
    --with-system-highlight \
    --with-python=/usr/bin/python 

make
make DESTDIR="$1" install
rm -f $1/usr/share/info/dir
