#!/bin/sh -uxe

patch -Np1 -i python-makefile.patch

export pkgdir=$1

make EXTRA="eeprog py-smbus"
make EXTRA="eeprog py-smbus" DESTDIR="/" PREFIX="$pkgdir/usr" sbindir="$pkgdir/usr/bin" install

install -Dm644 i2c-tools.sysusers "$1"/usr/lib/sysusers.d/i2c-tools.sysusers
install -Dm644 45-i2c-tools.rules "$1"/usr/lib/udev/rules.d/45-i2c-tools.rules
