#!/bin/sh -uxe
./configure \
	--prefix=/usr \
	--with-intl=system-icu \
	--shared-openssl \
	--shared-zlib \
	--shared-libuv \
	--experimental-http-parser \
	--shared-nghttp2 \
	--shared-cares \
    --shared-brotli

make
make DESTDIR="$1"  install
