#!/bin/sh -uxe
export DESTDIR="$1"

sed -i "s|if not version_info.contains('git')|if version_info.length() >= 4)|" server/meson.build
sed -i "/doxygen.sh/d" meson.build

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D gstreamer=no \
    -D manual=false

ninja -C build
ninja -C build install
