#!/bin/sh -uxe

source /etc/kiss-flags/multilib.sh

./configure \
    --build=i686-pc-linux-gnu \
    --host=i686-pc-linux-gnu \
    --prefix=/usr \
    --libdir=/usr/lib32 \
    --disable-documentation

make
make DESTDIR="$1" install

find "$1"/usr/include/*.h -not -name "*x86*" -exec rm -f {} +
