#!/bin/sh -uxe

for i in *.patch; do
    patch -Np1 -i $i
done

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --sbindir=/usr/bin \
    --disable-static

make
make DESTDIR="$1" install
