#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D dbus_policy_dir=/usr/share/dbus-1/system.d \
    -D gtk_doc=true \
    -D plugin_qcom_soc=disabled \
    -D polkit=permissive \
    -D vapi=true

ninja -C build
ninja -C build install
