#!/bin/sh -uxe
export DESTDIR="$1"

export CFLAGS+=' -flto -ffat-lto-objects'

cmake -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_BUILD_TYPE="None" \
    -Wno-dev

ninja -C build
ninja -C build install
