#!/bin/sh -uxe

export DESTDIR="$1"

export CFLAGS="-I$1/usr/include $CFLAGS"
export CXXFLAGS="-I$1/usr/include $CXXFLAGS"
export LDFLAGS="-L$1/usr/lib $LDFLAGS"

cd bad
meson build \
    -D prefix=/usr \
    -D openexr=disabled

ninja -C build
ninja -C build install
cd ..

cd good
meson build \
    -D prefix=/usr \
    -D qt5=disabled
ninja -C build
ninja -C build install
cd ..

cd ugly
meson build \
    -D prefix=/usr

ninja -C build 
ninja -C build install
