#!/bin/sh -uxe

./configure \
    --prefix=/usr

make V=1

make DESTDIR="$1" install

rm "$1"/usr/share/man/man3/history.3

install -Dm644 "$1"/usr/share/man/man3/editline.3 "$1"/usr/share/man/man3/el.3

