#!/bin/sh -uxe

source /etc/kiss-flags/multilib.sh

export CFLAGS+=" -fPIC -fno-strict-aliasing -fstack-protector-all -Wp,-I/usr/include/et"

cd src
patch -Np1 -i ../krb5-config_LDFLAGS.patch

./configure \
    --prefix=/usr \
    --host=i686-pc-linux-gnu \
    --sysconfdir=/etc \
    --localstatedir=/var/lib \
    --libdir=/usr/lib32 \
    --enable-shared \
    --with-system-et \
    --with-system-ss \
    --disable-rpath \
    --without-tcl \
    --enable-dns-for-realm \
    --with-ldap \
    --without-system-verto 


make
make DESTDIR="$1" install

rm -rf "$1"/usr/{include,share,bin,sbin}
