#!/bin/sh -uxe

export CPPFLAGS="-DSQLITE_ENABLE_COLUMN_METADATA=1 \
	    	-DSQLITE_ENABLE_UNLOCK_NOTIFY \
		-DSQLITE_ENABLE_DBSTAT_VTAB=1 \
		-DSQLITE_ENABLE_FTS3_TOKENIZER=1 \
		-DSQLITE_SECURE_DELETE \
		-DSQLITE_MAX_VARIABLE_NUMBER=250000 \
		-DSQLITE_MAX_EXPR_DEPTH=10000"

./configure --prefix=/usr \
	--disable-static \
	--disable-amalgamation \
	--enable-threadsafe \
	--enable-dynamic-extensions \
	--enable-fts3 \
	--enable-fts4 \
	--enable-fts5 \
	--enable-rtree \
	--enable-json1 

make

make DESTDIR="$1" install
