#!/bin/sh -uxe

export CFLAGS=${CFLAGS/-fno-plt}
export CXXFLAGS=${CXXFLAGS/-fno-plt}
export LDFLAGS=${LDFLAGS/,-z,now}

./configure \
    --prefix=/usr \
    --enable-glamor

make
make DESTDIR="$1" install
