#!/bin/sh -uxe
export DESTDIR="$1"

cmake -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_INSTALL_LIBDIR=/usr/lib \
    -D CMAKE_BUILD_TYPE=None \
    -D WITH_JAVA=OFF \
    -D WITH_JPEG8=ON \
    -Wno-dev

ninja -C build
ninja -C build install
