#!/bin/sh -uxe

sed -e '/certifi/d' \
    -e "s/,<.*'/'/" \
    -e '/charset_normalizer/d' \
    -i setup.py

patch -p1 -i certs.patch

python setup.py build
python setup.py install --skip-build -O1 --root="$1"
