#!/bin/sh -uxe

source /etc/kiss-flags/multilib.sh

autoreconf -fiv

./configure \
    --build=i686-pc-linux-gnu \
    --prefix=/usr \
    --libdir=/usr/lib32 \
    --disable-static \
    --disable-multi-os-directory \
    --disable-exec-static-tramp \
    --enable-pax_emutrap

make
make DESTDIR="$1" install

rm -rf "$1"/usr/{include,share}
