#!/bin/sh -uxe

./configure \
	--prefix=/ \
	--bindir=/usr/bin \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info \
	"CFLAGS=$CFLAGS" \
	"LDFLAGS=$LDFLAGS"
make
make DESTDIR="$1" install
rm -f $1/usr/share/info/dir
