#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D dbus-sys=/usr/share/dbus-1/system.d \
    -D default-pam-config=arch \
    -D default-path="/usr/bin:" \
    -D gdm-xsession=true \
    -D ipv6=true \
    -D plymouth=enabled \
    -D run-dir=/run/gdm \
    -D selinux=disabled 

ninja -C build
ninja -C build install

install -d "$1/var/lib"
install -d "$1/var/lib/gdm"                           -m1770
install -d "$1/var/lib/gdm/.config"                   -m700
install -d "$1/var/lib/gdm/.config/pulse"             -m700
install -d "$1/var/lib/gdm/.local"                    -m700
install -d "$1/var/lib/gdm/.local/share"              
install -d "$1/var/lib/gdm/.local/share/applications" 

# https://src.fedoraproject.org/rpms/gdm/blob/master/f/default.pa-for-gdm
install -t "$1/var/lib/gdm/.config/pulse" -m644 default.pa

install -Dm644 /dev/stdin "$1"/usr/lib/sysusers.d/gdm.conf << EOF
g gdm 120 -
u gdm 120 "Gnome Display Manager" /var/lib/gdm
EOF
