#!/bin/sh -uxe

export CFLAGS="${CFLAGS/-Werror=format-security/}"

sed -i "/^CFLAGS_NOOPT =/s/\$/ $CFLAGS/" -i unix/Makefile
sed -i "s|^LFLAGS1=''|LFLAGS1=$LDFLAGS|" -i unix/configure

patch -p1 -i zipnote.patch

make -j1 -f unix/Makefile prefix=/usr generic_gcc

make -j1 -f unix/Makefile prefix="$1"/usr \
    MANDIR="$1"/usr/share/man/man1 \
    install
