#!/bin/sh -uxe

sed -s "/init\.d/s|^|#|" misc/Makefile.in

./configure \
	--prefix=/usr \
	--with-root-prefix="" \
	--libdir=/usr/lib \
	--sbindir=/usr/bin \
	--enable-elf-shlibs \
	--disable-fsck \
	--disable-uuid \
	--disable-libuuid \
    --disable-libblkid

make

find po/ -name '*.gmo' -delete

make -C po update-gmo

make -j1 DESTDIR="$1" install install-libs

sed -i "s/^AWK=.*/AWK=awk/" "$1"/usr/bin/compile_et

sed -i 's|SS_DIR=.*|SS_DIR="/usr/share/ss"|' "$1"/usr/bin/mk_cmds
sed -i 's|SS_DIR=.*|SS_DIR="/usr/share/et"|' "$1"/usr/bin/compile_et

rm -f "$1"/usr/lib/lib{com_err,e2p,ext2fs,ss}.a

