#!/bin/sh -uxe
export DESTDIR="$1"

cmake -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_INSTALL_LIBDIR=lib \
    -D DOCTEST_WITH_TESTS=OFF

ninja -C build
ninja -C build install
