#!/bin/sh -uxe

patch -Np1 -i dynamiclib.patch

make

install -Dt "$1/usr/bin" snowball stemwords

install -Dt "$1/usr/lib" libstemmer.so.0.0.0

ln -s libstemmer.so.0.0.0 "$1/usr/lib/libstemmer.so.0"
ln -s libstemmer.so.0 "$1/usr/lib/libstemmer.so"

install -Dt "$1/usr/include" -m644 include/libstemmer.h

