#!/bin/sh -uxe

for i in *.patch; do 
	patch -Np1 -i $i
done

autoreconf -fiv

./configure \
	--prefix=/usr \
	--with-threads \
	--with-history \
	--with-python \
	--with-icu

sed -i "s| -shared | ${LDFLAGS}\0|g" libtool

make

find doc -type f -exec chmod -c 0644 {} +

make DESTDIR="$1" install

python -m compileall -d /usr/lib "$1"/usr/lib
python -O -m compileall -d /usr/lib "$1"/usr/lib
