#!/bin/sh -uxe
export DESTDIR="$1"

source /etc/kiss-flags/multilib.sh

cmake -S llvm -B build -G Ninja \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_CXX_FLAGS=-m32 \
    -D CMAKE_C_FLAGS=-m32 \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_SKIP_RPATH=ON \
    -D LLVM_BINUTILS_INCDIR=/usr/include \
    -D LLVM_BUILD_DOCS=OFF \
    -D LLVM_BUILD_LLVM_DYLIB=ON \
    -D LLVM_DEFAULT_TARGETS_TRIPLE="i686-pc-linux-gnu" \
    -D LLVM_ENABLE_BINDINGS=OFF \
    -D LLVM_ENABLE_FFI=ON \
    -D LLVM_ENABLE_RTTI=ON \
    -D LLVM_ENABLE_SPHINX=OFF \
    -D LLVM_ENABLE_PROJECTS="clang;llvm;libcxx;libclc;libcxxabi;polly;pstl" \
    -D LLVM_HOST_TRIPLE=$CHOST \
    -D LLVM_INCLUDE_BENCHMARKS=OFF \
    -D LLVM_LIBDIR_SUFFIX=32 \
    -D LLVM_LINK_LLVM_DYLIB=ON \
    -D LLVM_TARGET_ARCH=i686 \
    -Wno-dev 

ninja -C build
ninja -C build install

chmod -x "$1"/usr/lib32/*.a

mv "$1"/usr/bin/llvm-config "$1"/usr/lib32
mv "$1"/usr/include/llvm/Config/llvm-config.h "$1"/usr/lib32/llvm-config-32.h

rm -rf "$1"/usr/{bin,include,share/{doc,man,llvm,opt-viewer,clang,scan-build,scan-view},lib,libexec}

install -d "$1"/usr/include/llvm/Config
mv "$1"/usr/lib32/llvm-config-32.h "$1"/usr/include/llvm/Config/

mkdir "$1"/usr/bin
mv "$1"/usr/lib32/llvm-config "$1"/usr/bin/llvm-config32
