#!/bin/sh -uxe
export DESTDIR="$1"

# Fix compilation with meson >= 0.61
patch -Np1 -i 107.patch

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D selinux=false \
    -D wwan=false

ninja -C build
ninja -C build install
