#!/bin/sh -uxe

./configure \
	--prefix=/usr \
	--sbindir=/usr/bin \
	--libexecdir=/usr/lib \
	--with-rundir=/run/sudo \
	--with-vardir=/var/db/sudo \
	--with-logfac=auth \
	--enable-tmpfiles.d \
	--with-pam \
	--with-sssd \
	--with-ldap \
	--with-env-editor \
        --with-passprompt="[sudo:%p] Password: " \
	--with-all-insults

make
fakeroot make DESTDIR="$1" install

install -Dm644 sudo.pam "$1/etc/pam.d/sudo"
