#!/bin/sh -uxe

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-static \
    --with-encodingsdir=/usr/share/fonts/encodings

make
make DESTDIR="$1" install
