#!/bin/sh -uxe
export DESTDIR="$1"

cmake -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_BUILD_TYPE=None \
    -D BUILD_SHARED_LIBS=ON \
    -Wno-dev

ninja -C build
ninja -C build install
