#!/bin/sh -uxe

mkdir mozbuild

cat > .default-mozconfig << EOF
ac_add_options --enable-application=js
ac_add_options MOZ_OBJDIR=$PWD/obj
ac_add_options --prefix=/usr
ac_add_options --enable-release
ac_add_options --enable-hardening
ac_add_options --enable-optimize
ac_add_options --enable-rust-simd
ac_add_options --enable-linker=lld
ac_add_options --disable-bootstrap
ac_add_options --disable-debug
ac_add_options --disable-debug-symbols
ac_add_options --disable-jemalloc
ac_add_options --disable-strip

ac_add_options --with-system-zlib
ac_add_options --without-system-icu

ac_add_options --enable-readline
ac_add_options --enable-shared-js
ac_add_options --enable-tests
ac_add_options --with-intl-api
EOF

# 3-Tier PGO

export MOZ_NOSPAM=1
export MOZBUILD_STATE_PATH=$PWD/mozbuild
export MACH_USE_SYSTEM_PYTHON=1

export CC=clang
export CXX=clang++

echo "Profiling instrumented JS..."
cat > .mozconfig .default-mozconfig - << EOF
ac_add_options --enable-profile-generate=cross
EOF

./mach build
(
export js="$PWD/obj-$CHOST/dist/bin/js"
export LLVM_PROFILE_FILE="$PWD/js-%p-%m.profraw"

cd js/src/octane
"$js" run.js

cd ../../../third_party/webkit/PerformanceTests/ARES-6
"$js" cli.js

cd ../SunSpider/sunspider-0.9.1
"$js" sunspider-standalone-driver.js
)

llvm-profdata merge -o merged.profdata *.profraw

stat -c "Profile data found (%s bytes)" merged.profdata
test -s merged.profdata

echo "Removing instrumented js..."
./mach clobber

echo "Building optimized JS..."
cat > .mozconfig .default-mozconfig - << EOF
ac_add_options --enable-profile-use=cross
ac_add_options --with-pgo-profile-path=${PWD@Q}/merged.profdata
EOF

./mach build
cd obj-$CHOST
make DESTDIR="$1" install

rm $1/usr/lib/*.ajs || true
find $1/usr/{lib/pkgconfig,include} -type f -exec chmod -c a-x {} +
