#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
	--default-library shared \
	${MESON_OPTIONS}

ninja -C build
ninja -C build install

meson build-static \
	--default-library static

ninja -C build-static
ninja -C build-static install
