#!/bin/sh -uxe

# prepare for non-systemd initramfs
patch -Np1 --output='udev/69-dm-lvm-initcpio.rules.in' -i 0001-udev-initcpio.patch

# remove install section from systemd units that are enabled by default
sed -i -e '/^\[Install\]$/,$d' \
    scripts/dm_event_systemd_red_hat.socket.in \
    scripts/lvm2_lvmpolld_systemd_red_hat.socket.in \
    scripts/lvm2_monitoring_systemd_red_hat.service.in

./configure \
    CONFIG_SHELL=/usr/bin/bash \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --enable-cmdlib \
    --enable-dmeventd \
    --enable-lvmpolld \
    --enable-pkgconfig \
    --enable-readline \
    --enable-udev_rules \
    --enable-udev_sync \
    --with-cache=internal \
    --with-default-dm-run-dir=/run \
    --with-default-locking-dir=/run/lock/lvm \
    --with-default-pid-dir=/run \
    --with-default-run-dir=/run/lvm \
    --with-systemdsystemunitdir=/usr/lib/systemd/system \
    --with-thin=internal \
    --with-udev-prefix=/usr

make
make -C udev/ 69-dm-lvm-initcpio.rules

make DESTDIR="$1" install_device-mapper
# extra udev rule for device-mapper in initramfs
install -Dm644 11-dm-initramfs.rules "$1"/usr/lib/initcpio/udev/11-dm-initramfs.rules
make DESTDIR="$1" install_systemd_units
install -dm755 "${1}/usr/lib/systemd/system/sockets.target.wants"
ln -sf ../dm-event.socket "${1}/usr/lib/systemd/system/sockets.target.wants/dm-event.socket"

make DESTDIR="$1" install_lvm2

install -d "$1"/etc/lvm/{archive,backup}

install -Dm644 lvm2_install "$1"/usr/lib/initcpio/install/lvm2
ln -s lvm2 "$1"/usr/lib/initcpio/install/sd-lvm2
install -Dm644 udev/69-dm-lvm-initcpio.rules "$1"/usr/lib/initcpio/udev/69-dm-lvm.rules

install -d -m0755 "${1}/usr/lib/systemd/system/sysinit.target.wants/"
ln -sf ../lvm2-lvmpolld.socket "${1}/usr/lib/systemd/system/sysinit.target.wants/lvm2-lvmpolld.socket"
ln -sf ../lvm2-monitor.service "${1}/usr/lib/systemd/system/sysinit.target.wants/lvm2-monitor.service"

make DESTDIR="$1" install_systemd_generators

