#!/bin/sh

systemd-sysusers

chmod 4755 /usr/lib/polkit-1/polkit-agent-helper-1
chmod 4755 /usr/bin/pkexec

chmod 0700 -R /etc/polkit-1/rules.d
chmod 0700 -R /usr/share/polkit-1/rules.d

chown root:102 /{etc,usr/share}/polkit-1/rules.d
