#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    ${MESON_OPTIONS/--wrap-mode nodownload/} \
    -D docs=man \
    -D docs-build=true \
    -D systemddir=/usr/lib/systemd/system \
    -D udevrulesdir=/usr/lib/udev/rules.d

ninja -C build
ninja -C build install
