#!/bin/sh -uxe

patch -Np1 -i fix-libpam.patch
autoreconf -fsiv

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --mandir=/usr/share/man \
    --localstatedir=/var/run \
    --sysconfdir=/etc \
    --disable-account-tools-setuid \
    --with-libpam \
    --with-group-name-max-length=32 \
    --with-audit \
    --without-selinux 

make
make DESTDIR="$1" install

# Fix broken --sbindir.
mv -f "$1/usr/sbin/"* "$1/usr/bin"
rmdir "$1/usr/sbin"

#rm -r "$1"/etc/pam.d
# Remove evil/broken tools
rm "$1"/usr/bin/logoutd

# Remove utilities provided by util-linux
rm "$1"/usr/bin/login
rm "$1"/usr/bin/su
rm "$1"/usr/bin/chsh
rm "$1"/usr/bin/chfn
rm "$1"/usr/bin/sg
rm "$1"/usr/bin/nologin
rm "$1"/usr/bin/vipw
rm "$1"/usr/bin/vigr
# but we keep newgrp, as sg is really an alias to it
mv "$1"/usr/bin/{newgrp,sg}

install -Dm600 useradd.defaults "$1"/etc/default/useradd

# systemd units
install -Dm644 shadow.timer "$1"/usr/lib/systemd/system/shadow.timer
install -Dm644 shadow.service "$1"/usr/lib/systemd/system/shadow.service
install -dm755 "$1"/usr/lib/systemd/system/timers.target.wants

install -Dm644 login.defs "$1"/etc/login.defs
rm "$1"/etc/pam.d/*

install -t "$1"/etc/pam.d -m644 passwd chgpasswd chpasswd newusers

install -Dm644 etc/pam.d/groupmems "$1"/etc/pam.d/groupmems

for file in chage groupadd groupdel groupmod shadow useradd usermod userdel; do
    install -Dm644 defaults.pam "$1"/etc/pam.d/$file
done
