#!/bin/sh -uxe

patch -Np1 -i fix-libpam.patch
autoreconf -fsiv

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --mandir=/usr/share/man \
    --localstatedir=/var/run \
    --sysconfdir=/etc \
    --enable-utmpx \
    --enable-man \
    --enable-largefile \
    --enable-nls \
    --disable-account-tools-setuid \
    --with-group-name-max-length=32 \
    --with-sha-crypt \
    --with-btrfs \
    --with-bcrypt \
    --with-libpam \
    --without-fcaps \
    --with-audit \
    --with-nscd \
    --with-gnu-ld \
    --without-selinux 

make
make DESTDIR="$1" install

# Fix broken --sbindir.
mv -f "$1/usr/sbin/"* "$1/usr/bin"
rmdir "$1/usr/sbin"

#rm -r "$1"/etc/pam.d
# Remove evil/broken tools
rm "$1"/usr/bin/logoutd

# Remove utilities provided by util-linux
rm "$1"/usr/bin/login
rm "$1"/usr/bin/su
rm "$1"/usr/bin/chsh
rm "$1"/usr/bin/chfn
rm "$1"/usr/bin/sg
rm "$1"/usr/bin/nologin
rm "$1"/usr/bin/vipw
rm "$1"/usr/bin/vigr
# but we keep newgrp, as sg is really an alias to it
#mv "$1"/usr/bin/{newgrp,sg}
