#!/bin/sh -uxe
export DESTDIR="$1"
git fetch

# don't claim the compass sensor when not needed
git cherry-pick -n 34a67b676d24

for i in *.patch; do
    patch -Np1 -i $i
done

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D dbus-srv-user=geoclue \
    -D dbus-sys-dir=/usr/share/dbus-1/system.d  

ninja -C build
ninja -C build install

echo ' u geoclue - "Geoinformation service" /var/lib/geoclue' | \
    install -Dm644 /dev/stdin "$1"/usr/lib/sysusers.d/geoclue.conf

echo 'd /var/lib/geoclue 0755 geoclue geoclue' |  \
    install -Dm644 /dev/stdin "$1"/usr/lib/tmpfiles.d/geoclue.conf
