#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D dbus-srv-user=geoclue \
    -D dbus-sys-dir=/usr/share/dbus-1/system.d  

ninja -C build
ninja -C build install

echo 'u geoclue - "Geoinformation service" /var/lib/geoclue' | \
    install -Dm644 /dev/stdin "$1"/usr/lib/sysusers.d/geoclue.conf

echo 'd /var/lib/geoclue 0755 geoclue geoclue' |  \
    install -Dm644 /dev/stdin "$1"/usr/lib/tmpfiles.d/geoclue.conf
