#!/bin/sh -uxe
export DESTDIR="$1"

cmake -B build -G Ninja \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D BUILD_SHARED_LIBS=ON \
    -D BUILD_STATIC_LIBS=OFF \
    -D BUILD_DOC=ON

ninja -C build
ninja -C build install
