#!/bin/sh -uxe

cat >> doc/sample.wgetrc << EOF
# Default CA location
ca_certificate=/etc/ssl/certs/ca-certificates.crt
EOF

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-rpath \
    --enable-nls \
    --with-ssl=gnutls

make
make DESTDIR="$1" install 

rm -f $1/usr/share/info/dir
