#!/bin/sh -uxe

./configure \
	--libdir=/usr/lib \
	--sbindir=/usr/bin \
	--enable-shared \
	--enable-unix \
	--enable-pamlocking \
	--enable-usergroups \
	--enable-largefile \
	--enable-nls \
	--disable-db

make
make DESTDIR="$1" install

# Delete systemd service
rm -rf "$1/usr/lib/systemd"

install -Dm644 su.pamd                          "$1/etc/pam.d/su"
install -Dm644 other.pamd                       "$1/etc/pam.d/other"
install -Dm644 base-auth.pamd                   "$1/etc/pam.d/base-auth"
install -Dm644 base-account.pamd                "$1/etc/pam.d/base-account"
install -Dm644 base-session.pamd                "$1/etc/pam.d/base-session"
install -Dm644 base-password.pamd               "$1/etc/pam.d/base-password"
install -Dm644 system-login.pamd                "$1/etc/pam.d/system-login"
install -Dm644 system-login.pamd		"$1/etc/pam.d/system-auth"
install -Dm644 system-local-login.pamd          "$1/etc/pam.d/system-local-login"
install -Dm644 base-session-noninteractive.pamd "$1/etc/pam.d/base-session-noninteractive"
