#!/bin/sh -uxe

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --sbindir=/usr/bin \
    --enable-unix \
    --enable-shared \
    --enable-largefile \
    --enable-pamlocking \
    --enable-usergroups \
    --enable-nls \
    --disable-db

make
make DESTDIR="$1" install

# Delete a systemd service file
rm -rf "$1/usr/lib/systemd"
mkdir -p "$1/etc/pam.d/"
for i in *.pamd; do
	mv $i "$1"/etc/pam.d/$i
done

