#!/bin/sh -uxe

# Disable development mode
sed -i '/^development=/s/true/false/' bfd/development.sh

# Fix malformed archive error with nodejs
patch -Np1 -i 0001-close-thin-archive-fd.patch

./configure \
	--prefix=/usr \
	--with-lib-path=/usr/lib:/usr/local/lib \
	--enable-deterministic-archives \
	--enable-gold \
	--enable-cet \
	--enable-relro \
	--without-debuginfod \
	--enable-threads \
	--enable-lto \
	--enable-ld=default \
	--enable-plugins \
	--enable-multilib \
	--enable-gdb \
	--enable-nls \
	--enable-readline \
	--disable-gprof \
	--disable-werror \
	--with-mmap \
	--with-pic \
	--with-system-zlib

make configure-host
make tooldir=/usr
make DESTDIR="$1" tooldir=/usr install

echo 'INPUT( /usr/lib/libbfd.a -liberty -lz -ldl )' > "$1/usr/lib/libbfd.so"
echo 'INPUT( /usr/lib/libopcodes.a -lbfd )' > "$1/usr/lib/libopcodes.so"
rm -f $1/usr/share/info/dir
