#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D afp=false \
    -D afc=false \
    -D bluray=false \
    -D cdda=false \
    -D nfs=false

ninja -C build
ninja -C build install

