#!/bin/sh -uxe
export DESTDIR="$1"

# Fix build with meson >= 0.61
patch -Np1 -i meson.patch 

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D afp=false \
    -D afc=false \
    -D bluray=false \
    -D smb=false \
    -D cdda=false \
    -D nfs=false

ninja -C build
ninja -C build install

