#!/bin/sh -uxe
export DESTDIR="$1"

cmake -B build -G Ninja \
    -D FREEGLUT_BUILD_STATIC_LIBS=OFF \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_INSTALL_LIBDIR=lib \
    -D CMAKE_BUILD_TYPE=None 

ninja -C build
ninja -C build install
