#!/bin/sh -uxe

for i in *.patch; do
    patch -Np1 -i $i
done

./configure \
    --prefix=/usr \
    --disable-fd-passing \
    --disable-static \
    --disable-gpgsm-test

make

make DESTDIR="$1" install
