#!/bin/sh -uxe

sed -i "s|-Werror||" src/Makefile.am

NOCONFIGURE=1 ./autogen.sh

mkdir gtk2
mkdir gtk3

cd gtk2 
../configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --with-gtk=2 \
    --enable-gtk-doc \
    --disable-introspection

sed -i "s| -shared | ${LDFLAGS}\0|g" libtool

make -j1
make DESTDIR="$1" -j1 install

cd ../gtk3
../configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --with-gtk=3 \
    --enable-gtk-doc

sed -i "s| -shared | ${LDFLAGS}\0|g" libtool

make -j1
make DESTDIR="$1" -j1 install
