#!/bin/sh -uxe

src=$PWD

cd unix

./configure \
	--prefix=/usr \
	--mandir=/usr/share/man \
	--enable-threads \
	--disable-rpath \
	--enable-64bit

make
make INSTALL_ROOT="$1" install  install-private-headers

ln -sf wish${2%.*} "$1"/usr/bin/wish
ln -sf libtk${2%.*} "$1"/usr/lib/libtk.so

cd ..
for dir in compat generic generic/ttk unix; do
    install -dm755 "$1"/usr/include/tk-private/$dir
    install -m644 -t "$1"/usr/include/tk-private/$dir $dir/*.h
done

sed -e "s|${src}/tk${2}/unix|/usr/lib|" \
    -e "s|${src}/tk${2}|/usr/include|" \
    -i "${1}/usr/lib/tkConfig.sh"

