#!/bin/sh -uxe

for i in *.patch; do
    patch -Np1 -i $i
done

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --libexecdir=/usr/lib/polkit-gnome 

make
make DESTDIR="$1" install

install -Dm644 polkit-gnome-authentication-agent-1.desktop \
    "$1"/usr/share/applications/polkit-gnome-authentication-agent-1.desktop
