#!/bin/sh -uxe
export DESTDIR="$1"

# Minimal debug info; #6229
export CFLAGS+=" -g1 -mtls-dialect=gnu -flto=auto -ffat-lto-objects"
export CXXFLAGS+=" -g1 -mtls-dialect=gnu -flto=auto -ffat-lto-objects"

meson build \
    -D b_ndebug=true \
    -D platforms=x11,wayland \
    -D gallium-drivers=r300,r600,radeonsi,nouveau,virgl,svga,swrast,iris,crocus,zink \
    -D vulkan-drivers=amd,intel,swrast \
    -D vulkan-layers=device-select,intel-nullhw,overlay \
    -D dri3=enabled \
    -D egl=enabled \
    -D gallium-extra-hud=true \
    -D gallium-nine=true \
    -D gallium-omx=bellagio \
    -D gallium-opencl=icd \
    -D gallium-va=enabled \
    -D gallium-vdpau=enabled \
    -D gallium-xa=enabled \
    -D gallium-xvmc=disabled \
    -D gbm=enabled \
    -D gles1=disabled \
    -D gles2=enabled \
    -D glx=dri \
    -D glvnd=true \
    -D libunwind=enabled \
    -D llvm=enabled \
    -D shared-llvm=enabled \
    -D lmsensors=enabled \
    -D osmesa=true \
    -D shared-glapi=enabled \
    -D microsoft-clc=disabled \
    -D valgrind=enabled \
    ${MESON_OPTIONS}

meson configure build

ninja -C build
ninja -C build install
