#!/bin/sh -uxe

NOCONFIGURE=1 ./autogen.sh

./configure \
    --disable-zram \
    --prefix=/usr \
    --sysconfdir=/etc \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib \
    --with-systemdsystemunitdir=/usr/lib/systemd/system \
    --localstatedir=/var \
    --disable-static \
    --enable-gtk-doc \
    enable_available_modules=yes

make
make DESTDIR="$1" install
