#!/bin/sh -uxe

cd libbpf 
git fetch --unshallow
cd ..

cd pahole
patch -p1 -i ../python.diff

git submodule init
git submodule set-url lib/bpf $PWD/../libbpf
git submodule update
cd ..

cmake -S pahole -B build -G Ninja \
	-D CMAKE_INSTALL_PREFIX=/usr \
	-D CMAKE_BUILD_TYPE=None \
	-D __LIB=lib 

ninja -C build
ninja -C build install

python -m compileall -d / "$1"
python -O -m compileall -d / "$1"
