#!/bin/sh -uxe

cp /usr/include/linux/audit.h lib/audit.h

patch -p1 -i audit-3.0.8-flex-array-workaround.patch

./configure \
	--prefix=/usr \
	--sbindir=/usr/bin \
	--sysconfdir=/etc \
	--libexecdir=/usr/lib/audit \
	--enable-gssapi-krb5=yes \
	--enable-systemd=yes \
	--with-libcap-ng=yes

make

make DESTDIR="$1" INSTALL="install -p" install

cd "$1"
install -dm700 var/log/audit

rm -rf etc/rc.d \
    etc/sysconfig \
    usr/lib/audit 

sed -ri 's|/sbin|/usr/bin|' \
	etc/audit/*.conf \
	etc/audit/plugins.d/*.conf 

chmod 644 usr/lib/systemd/system/auditd.service
