#!/bin/sh -uxe

for i in *.patch; do
    patch -Np1 -i  $i
done

autoreconf -fiv

./configure \
    --prefix=/usr \
    --disable-static \
    --with-icu-config=/usr/bin/icu-config

sed -i "s| -shared | ${LDFLAGS}\0|g" libtool

make
make DESTDIR="$1" install
