#!/bin/sh -uxe
export DESTDIR="$1"
export CFLAGS="${CFLAGS/-fexceptions/} -flto=auto -ffat-lto-objects"
export CXXFLAGS="${CXXFLAGS/-fexceptions/} -flto=auto -ffat-lto-objects"

meson build \
    ${MESON_OPTIONS} \
    -D graphite2=enabled

ninja -C build
ninja -C build install
