#!/bin/sh -uxe
export DESTDIR="$1"

export CXXFLAGS="${CXXFLAGS} -fpermissive"
export LIBPOSTFIX=/

patch -p1 -i ghostscript918.patch

cmake -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr

ninja -C build
ninja -C build install
