#!/bin/sh -uxe

autoreconf -fiv

./configure \
	--prefix=/usr \
	--sysconfdir=/etc/syslog \
	--sbindir=/usr/bin \
	--libexecdir=/usr/bin \
	--localstatedir=/var/run/syslog \
	--datadir=/usr/share \
	--with-pidfile-dir=/var/run \
	--with-python=3

make
make DESTDIR="$1" install
chmod +s "$1"/usr/bin/syslog-ng

install -Dm644 syslog-ng.conf "$1"/etc/syslog/syslog-ng.conf
install -Dm644 syslog-ng.logrotate "$1"/etc/syslog/syslog-ng.logrotate
