#!/bin/sh -uxe

# Fix compilation with C++11 and newer
patch -Np1 -i libvisual-0.4.0-inlinedefineconflict.patch
export CFLAGS="${CFLAGS/-Werror/-Wno-error}"

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install
