#!/bin/sh -uxe

for i in *.patch; do
    patch -p1 -i $i
done

autoreconf -fiv

UDEV_RULES_PATH=/usr/lib/udev/rules.d MOUNT_FUSE_PATH=/usr/bin ./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --enable-lib \
    --enable-util \
    --disable-example

make
make DESTDIR="$1" install

rm -rf "$1"/dev
