#!/bin/sh -uxe
export DESTDIR="$1"

git fetch

git submodule update --init --recursive

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D docs=true \
    -D packagekit=false

ninja -C build
ninja -C build install
