#!/bin/sh -uxe

./autogen.sh \
    --prefix=/usr \
    --with-xkb-bin-base=/usr/bin \
    --with-xkb-base=/usr/share/X11/xkb \
    --disable-static \
    --enable-gtk-doc

make
make DESTDIR="$1" install
