#!/bin/sh -uxe

./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--localstatedir=/var \
    --runstatedir=/run \
	--with-system-socket=/var/run/dbus/system_bus_socket \
	--with-system-pid-file=/var/run/dbus/pid \
	--with-console-auth-dir=/var/run/console \
    --enable-systemd \
	--enable-assert \
	--enable-doxygen-docs \
	--enable-inotify \
	--enable-user-session \
	--enable-x11-autolaunch

make
make DESTDIR="$1" install

echo 'u dbus 81 "System Message Bus"' | install -Dm644 /dev/stdin "$1"/usr/lib/sysusers.d/dbus.conf
