#!/bin/sh -uxe
autoreconf -fiv

./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--enable-deterministic-archives \
	--disable-debuginfod

make
make DESTDIR="$1" install

rm -rf "$1"/etc/profile.d/debuginfod.*
