#!/bin/sh -uxe

mkdir obj
for i in *.patch; do
    patch -Np1 -i $i
done

export config_args=(
    --prefix=/usr
    --disable-debug
    --disable-debug-symbols
    --disable-jemalloc
    --disable-strip
    --enable-hardening
    --enable-linker=lld
    --enable-optimize
    --enable-readline
    --enable-release
    --disable-rust-simd
    --enable-shared-js
    --disable-tests
    --with-intl-api
    --with-system-zlib
    --without-system-icu
)
export CC=clang
export CXX=clang++
export AR=llvm-ar
export NM=llvm-nm

# 3-Tier PGO
cd obj
echo "Building instrumented JS"
sh ../js/src/configure "${config_args[@]}" \
    --enable-profile-generate=cross

make

echo "Profiling instrumented JS..."

(
export js="$PWD/dist/bin/js"
export LLVM_PROFILE_FILE="$PWD/js-%p-%m.profraw"

cd ../js/src/octane
"$js" run.js

cd ../../../third_party/webkit/PerformanceTests/ARES-6
"$js" cli.js

cd ../SunSpider/sunspider-0.9.1
"$js" sunspider-standalone-driver.js
)

llvm-profdata merge -o merged.profdata *.profraw

stat -c "Profile data found (%s bytes)" merged.profdata
test -s merged.profdata

echo "Removing instrumented js..."
make clobber

echo "Building optimized JS..."
sh ../js/src/configure "${config_args[@]}" \
    --enable-lto=cross \
    --enable-profile-use=cross \
    --with-pgo-profile-path="$PWD/merged.profdata"

make
make DESTDIR="$1" install

rm $1/usr/lib/*.ajs || true
find $1/usr/{lib/pkgconfig,include} -type f -exec chmod -c a-x {} +
