#!/bin/sh -uxe
export DESTDIR="$1"

cmake -B build -G Ninja \
    -D BUILD_SHARED_LIBS=ON \
    -D LLVM_SPIRV_BUILD_EXTERNAL=YES \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_POSITION_INDEPENDENT_CODE=ON \
    -D CMAKE_SKIP_RPATH=ON \
    -Wno-dev

ninja -C build
ninja -C build llvm-spirv
ninja -C build install
install -Dm755 build/tools/llvm-spirv/llvm-spirv "$1/usr/bin/llvm-spirv"
