#!/bin/sh -uxe
source /etc/kiss-flags/multilib.sh

./configure \
    --prefix=/usr \
    --libdir=/usr/lib32 \
    --disable-rpath \
    --disable-werror

make
make DESTDIR="$1" install

rm -rf "$1"/usr/{bin,include,share}
