#!/bin/sh -uxe
export DESTDIR="$1"

#./configure \
    #--prefix=/usr \
    #--sysconfdir=/etc \
    #--localstatedir=/var \
    #--libexecdir=/usr/lib \
    #--disable-static \
    #--enable-gtk-doc

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D gtk-doc=true \
    -D idevice=disabled

ninja -C build
ninja -C build install
