#!/bin/sh -uxe
export DESTDIR="$1"

# Fix build with meson >= 0.61.0
patch -Np1 -i 755fd758f866d3a3f7ca482942beee749f13a91e.diff
meson build \
    ${MESON_OPTIONS} \
    -D gtk_doc=true \
    -D icon_update=false

ninja -C build
ninja -C build install

