#!/bin/sh -uxe
export DESTDIR="$1"

patch -Np1 -i rawtherapee-glibc-2.34.patch

cmake -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_NAME_SUFFIX=""

ninja -C build
ninja -C build install
