#!/bin/sh -uxe

source /etc/kiss-flags/multilib.sh

autoreconf -fiv

./configure \
    --prefix=/usr \
    --disable-static \
    --libdir=/usr/lib32

make
make DESTDIR="$1" install

rm -rf "$1"/usr/{include,share,bin}
