#!/bin/sh -uxe

./configure \
    --prefix=/usr \
    --disable-static \
    --disable-jpg-shared \
    --disable-png-shared \
    --disable-tif-shared \
    --disable-webp-shared

make
make DESTDIR="$1" install
