#!/bin/sh -uxe
sed -i "/MANDIR =/s|)|)/share|" unix/Makefile

for i in *.patch; do
    patch -p1 -i $i
done

DEFINES='-DACORN_FTYPE_NFS -DWILD_STOP_AT_DIR -DLARGE_FILE_SUPPORT \
    -DUNICODE_SUPPORT -DUNICODE_WCHAR -DUTF8_MAYBE_NATIVE -DNO_LCHMOD \
    -DDATE_FORMAT=DF_YMD -DUSE_BZIP2 -DNOMEMCPY -DNO_WORKING_ISPRINT'

make -f unix/Makefile prefix=/usr \
    D_USE_BZ2=-DUSE_BZIP2 L_BZ2=-lbz2 \
    LF2="$LDFLAGS" CF="$CFLAGS  -I. $DEFINES" \
    unzips

make -f unix/Makefile prefix="$1/usr" install
