#!/bin/sh -uxe

autoreconf -fiv

./configure \
	--prefix=/usr \
	--bindir=/usr/bin \
	--sysconfdir=/etc \
	--sbindir=/usr/bin \
	--with-rootrundir=/var/run \
	--enable-hwdb
	
make
make DESTDIR="$1" install
