#!/bin/sh -uxe

source /etc/kiss-flags/multilib.sh

cd icu4c/source

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --libdir=/usr/lib32

make
make DESTDIR="$1" install

rm -rf "$1"/usr/{include,sbin,share}

# keep icu-config-32
find "$1"/usr/bin -type f -not -name icu-config -delete
mv "$1"/usr/bin/icu-config{,32}
