#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    ${MESON_OPTIONS} \
    --buildtype release \
    -D crypto-library=nss \
    -D crypto-library-kdf=disabled

ninja -C build
ninja -C build install
