#!/bin/sh -uxe
export DESTDIR="$1"

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --with-mapdir=/usr/share/fonts/util \
    --with-fontrootdir=/usr/share/fonts

make
make DESTDIR="$1" install
