#!/bin/sh -uxe
export DESTDIR="$1"

export CFLAGS+=" -DG_DISABLE_CAST_CHECKS"

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D broadway-backend=true \
    -D cloudproviders=enabled \
    -D tracker=enabled \
    -D colord=enabled \
    -D gtk_doc=true \
    -D man-pages=true \
    --buildtype plain 

ninja -C build
ninja -C build install

install -Dm644 /dev/stdin "$1/usr/share/gtk-4.0/settings.ini" << EOF
[Settings]
gtk-icon-theme-name = Adwaita
gtk-theme-name = Adwaita 
gtk-font-name = Cantarell 11
EOF
