#!/bin/sh -uxe
export DESTDIR="$1"

sed -i "s|^modprobedir =.*|modprobedir = /usr/lib/modprobe.d/|" contrib/meson.build

export CFLAGS+=" -ffat-lto-objects" 

meson build \
    ${MESON_OPTIONS}

ninja -C build
ninja -C build install
