#!/bin/sh -uxe

sed -i "s|^modprobedir =.*|modprobedir = /usr/lib/modprobe.d/|" Makefile.am

./autogen.sh

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-docs \
    --with-systemd

make
make DESTDIR="$1" install
