#!/bin/sh -uxe

sed -i "s|^modprobedir =.*|modprobedir = /usr/lib/modprobe.d/|" Makefile.am

patch -p1 -i *.patch

./autogen.sh

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-docs \
    --without-systemd

make
make DESTDIR="$1" install
