#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D udev-dir=/usr/lib/udev \
    -D tests=false \
    -D documentation=false

ninja -C build
ninja -C build install
