#!/bin/sh -uxe
export DESTDIR="$1"

# fix build with meson >= 0.61
patch -Np1 -i b60dad3c2536c17bd201f74ad8e40eb74385ed9f.patch

meson build \
    ${MESON_OPTIONS}

ninja -C build
ninja -C build install
