#!/bin/sh -uxe

./configure --prefix=/usr \
    --sbin=/usr/bin \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --disable-static \
    --enable-shared \
    --enable-alwaystrue \
    --enable-checkapop \
    --enable-cram \
    --enable-digest \
    --disable-otp \
    --disable-srp \
    --disable-srp-setpass \
    --disable-krb4 \
    --enable-gssapi \
    --enable-auth-sasldb \
    --enable-plain \
    --enable-anon \
    --enable-login \
    --enable-ntlm \
    --disable-passdss \
    --with-sqlite3=/usr/lib \
    --enable-ldapdb \
    --disable-macos-framework \
    --with-pam \
    --with-saslauthd=/var/run/saslauthd \
    --with-ldap \
    --with-dblib=lmdb \
    --with-configdir=/etc/sasl2:/etc/sasl:/usr/lib/sasl2 \
    --sysconfdir=/etc \
    --with-devrandom=/dev/urandom

make
make DESTDIR="$1" install
