#!/bin/sh -uxe

autoreconf -fiv

./configure --prefix=/usr \
    --sbin=/usr/bin \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --disable-static \
    --enable-shared \
    --enable-alwaystrue \
    --enable-checkapop \
    --enable-cram \
    --enable-digest \
    --disable-otp \
    --disable-srp \
    --disable-srp-setpass \
    --disable-krb4 \
    --enable-gssapi \
    --enable-auth-sasldb \
    --enable-plain \
    --enable-anon \
    --enable-login \
    --enable-ntlm \
    --disable-passdss \
    --enable-sql \
    --with-mysql=/usr \
    --with-pgsql=/usr/lib \
    --with-sqlite3=/usr/lib \
    --enable-ldapdb \
    --disable-macos-framework \
    --with-pam \
    --with-saslauthd=/var/run/saslauthd \
    --with-ldap \
    --with-mysql=/usr \
    --with-pgsql=/usr \
    --with-dblib=gdbm \
    --with-configdir=/etc/sasl2:/etc/sasl:/usr/lib/sasl2 \
    --sysconfdir=/etc \
    --with-devrandom=/dev/urandom

sed -i "s| -shared | ${LDFLAGS}\0|g" libtool

make
make DESTDIR="$1" install

install -Dm644 saslauthd.conf.d "$1"/etc/conf.d/saslauthd
install -Dm644 saslauthd.service "$1"/usr/lib/systemd/system/saslauthd.service
install -Dm644 tmpfiles.conf "$1"/usr/lib/tmpfiles.d/saslauthd.conf
