#!/bin/sh -uxe

NOCONFIGURE=1 ./autogen.sh

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-schemas-compile \
    --disable-static

sed -i "s| -shared | ${LDFLAGS}\0|g" libtool

make
make DESTDIR="$1" install
