#!/bin/sh

echo "-> creating mysql user and folders..."

mkdir /var/lib/mysql
useradd -r -d /var/lib/mysql -s /bin/false mysql 
mysql_install_db --force --datadir=/var/lib/mysql --user=mysql 

chown -R mysql:mysql /var/lib/mysql

cat << EOF
-> To set up mariadb, first start the service using /etc/init.d/mysql,
-> then use # mysql_secure_installation and follow its prompts.
-> The default root password is empty.
-> Afterwards connect to the database using $ mysql -u root -p
EOF
