#!/bin/sh -uxe
export DESTDIR="$1"

cmake -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D LIBEXEC_INSTALL_DIR=/usr/lib \
    -D SYSCONF_INSTALL_DIR=/etc \
    -D ENABLE_INTROSPECTION=ON \
    -D ENABLE_VALA_BINDINGS=ON \
    -D ENABLE_GTK_DOC=OFF \
    -D WITH_PHONENUMBER=OFF

ninja -C build
ninja -C build install
