#!/bin/sh -uxe

rm -f intel-ucode{,with-caveats}/list

mkdir -p kernel/x86/microcode
iucode_tool --write-earlyfw=intel-ucode.img intel-ucode{,-with-caveats}

install -Dm0644 intel-ucode.img "$1/boot/intel-ucode.img"
