#!/bin/sh -uxe

python setup.py build
python setup.py install --root="$1" --optimize=1 --skip-build

install -Dt "$1"/usr/share/bash-completion/completions -m644 data/shell-completions/bash/*
install -Dt "$1"/usr/share/zsh/site-functions -m644 data/shell-completions/zsh/*
