#!/bin/sh -uxe

./configure --prefix=/usr \
    --disable-static \
    --with-idn \
    --enable-openssl-compatibility \
    --enable-guile \
    --with-guile-site-dir=no \
    --with-included-libtasn1 \
    --with-included-unistring \
    --with-p11-kit

sed -i "s| -shared | ${LDFLAGS}\0|g" libtool

make
make DESTDIR="$1" install
rm -f $1/usr/share/info/dir
