#!/bin/sh -uxe

patch -Rp1 -i *.patch

_samba4_idmap_modules=idmap_ad,idmap_rid,idmap_adex,idmap_hash,idmap_tdb2
_samba4_pdb_modules=pdb_tdbsam,pdb_ldap,pdb_ads,pdb_smbpasswd,pdb_wbc_sam,pdb_samba4
_samba4_auth_modules=auth_unix,auth_wbc,auth_server,auth_netlogond,auth_script,auth_samba4

./configure \
    --color=yes \
    --enable-fhs \
    --prefix=/usr \
    --sysconfdir=/etc \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --libexecdir=/usr/lib/samba \
    --localstatedir=/var \
    --with-configdir=/etc/samba \
    --with-lockdir=/var/cache/samba \
    --with-sockets-dir=/run/samba \
    --with-piddir=/run \
    --with-ads \
    --with-ldap \
    --with-winbind \
    --with-acl-support \
    --with-systemd \
    --systemd-install-services \
    --with-pam \
    --with-pammodulesdir=/usr/lib/security \
    --bundled-libraries=!tdb,!talloc,!pytalloc-util,!tevent,!popt,!ldb,!pyldb-util \
    --with-shared-modules=${_samba4_idmap_modules},${_samba4_pdb_modules},${_samba4_auth_modules} \
    --disable-rpath-install \
    --with-cluster-support \
    --with-profiling-data

make
make DESTDIR="$1" install

if [ ! -e "$1"/usr/bin/smbtar ]; then
    install -m755 source3/script/smbtar "$1"/usr/bin
fi

mkdir -p "$1"/usr/lib/cups/backend
ln -sf /usr/bin/smbspool "$1"/usr/lib/cups/backend/smb

for script in bin/samba_dnsupdate bin/samba_kcc bin/samba_spnupdate bin/samba_upgradedns bin/samba-tool;
do
    sed -i "/^sys\.path\.insert/ a\
sys.path.insert(0, '/usr/lib/python3.10/site-packages')" \
               "${1}"/usr/${script}
done

sed -i -e '/^EnvironmentFile/ s/sysconfig/conf.d/' "${1}"/usr/lib/systemd/system/*.service
install -d -m755  "${1}"/etc/conf.d
install -Dm644 packaging/systemd/samba.sysconfig "${1}"/etc/conf.d/samba

install -Dm644 samba.conf "$1"/usr/lib/tmpfiles.d/samba.conf
install -dm755 "$1"/etc/samba

mkdir -p "$1"/etc/samba/private
chmod 700 "$1"/etc/samba/private

install -Dm644 samba.logrotate "$1"/etc/logrotate.d/samba
install -Dm644 samba.pam "$1"/etc/pam.d/samba

install -dm1777 "$1"/var/spool/samba

chmod 750 "$1"/etc/sudoers.d
chmod 600 "$1"/etc/sudoers.d/ctdb
