#!/bin/sh -uxe
export DESTDIR="$1"

export CFLAGS+=" -flto=auto -ffat-lto-objects"
export CXXFLAGS+=" -flto=auto -ffat-lto-objects"

meson build \
	${MESON_OPTIONS} \
	-D docs=enabled \
    -D gresource_quirks=disabled \
	-D plugin_intel_spi=true \
	-D supported_build=enabled \
	-D efi_binary=false

ninja -C build
ninja -C build install

rm -r "$1"/usr/share/installed-tests

mv "$1"/usr/bin/{,fwupd-}dbxtool
mv "$1"/usr/share/man/man1/{,fwupd-}dbxtool.1

rm "$1"/usr/lib/modules-load.d/fwupd-msr.conf
