#!/bin/sh -uxe

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --without-python

make
make DESTDIR="$1" install

mkdir -p "$1/usr/share/dict"

ln -sf /usr/share/cracklib/cracklib-small "$1/usr/share/dict/cracklib-small"

sh ./util/cracklib-format dicts/cracklib-small | sh ./util/cracklib-packer "$1/usr/share/cracklib/pw_dict"
