#!/bin/sh

chown -R root.root "$1/var/log/journal"

sd_booted() {
  [[ -d run/systemd/system && ! -L run/systemd/system ]]
}

add_journal_acls() {
  # ignore errors, since the filesystem might not support ACLs
  setfacl -Rnm g:wheel:rx,d:g:wheel:rx,g:adm:rx,d:g:adm:rx var/log/journal/ 2>/dev/null
  :
}

post_common() {
  journalctl --update-catalog
}

_242_0_2_changes() {
  if [[ -L var/lib/systemd/timesync ]]; then
    rm var/lib/systemd/timesync
    if [[ -d var/lib/private/systemd/timesync ]]; then
      mv var/lib/{private/,}systemd/timesync
    fi
  fi
}

post_install() {
  systemd-machine-id-setup

  post_common "$@"

  add_journal_acls

  # enable some services by default, but don't track them
  systemctl enable \
    getty@tty1.service \
    remote-fs.target

  echo ":: Append 'init=/usr/lib/systemd/systemd' to your kernel command line in your"
  echo "   bootloader to replace sysvinit with systemd, or install systemd-sysvcompat"

  mkdir -m2755 var/log/journal/remote
  chgrp systemd-journal-remote var/log/journal/remote
}

post_install 250
