#!/bin/sh -uxe

source /etc/kiss-flags/multilib.sh
export CFLAGS+=" -O1"

NOCONFIGURE=1 ./autogen.sh

./configure \
    --prefix=/usr \
    --libdir=/usr/lib32 \
    --disable-static \
    --enable-xinput \
    --enable-xkb 

make
make DESTDIR="$1" install

rm -rf "$1"/usr/{include,share}
