#!/bin/sh -uxe

git submodule init
git submodule update --recursive

for i in *.patch; do
    patch -Np1 -i $i
done

sed -i "s|/usr/include/catch|/usr/include/catch2|g" configure.ac

autoreconf -fiv

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --sys=/etc \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --disable-systemd \
    --enable-elogind \
    --with-bundled-catch \
    --with-bundled-pegtl \
    --with-dbus \
    --with-polkit \
    --with-crypto-library=sodium

make
touch rules.conf
make DESTDIR="$1" install

chmod 750 "$1/etc/usbguard"

install -Dpm600 usbguard-daemon.conf rules.conf -t "$1/etc/usbguard"

install -Dpm644 scripts/bash_completion/usbguard -t "$1/usr/share/bash-completion/completions" 

install -Dpm644 scripts/usbguard-zsh-completion "$1/usr/share/zsh/site-functions/_usbguard"


