#!/bin/sh -uxe

git submodule init
git submodule update --recursive

autoreconf -fiv

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --sys=/etc \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --enable-systemd \
    --with-bundled-catch \
    --with-bundled-pegtl \
    --with-dbus \
    --with-polkit \
    --with-crypto-library=sodium

make
touch rules.conf
make INSTALL='install -p' DESTDIR="$1" install

chmod 750 "$1/etc/usbguard"

install -Dpm600 usbguard-daemon.conf rules.conf -t "$1/etc/usbguard"

install -Dpm644 scripts/bash_completion/usbguard -t "$1/usr/share/bash-completion/completions" 

install -Dpm644 scripts/usbguard-zsh-completion "$1/usr/share/zsh/site-functions/_usbguard"
