#!/bin/sh -uxe
export DESTDIR="$1"
export CFLAGS+=" -ffat-lto-objects"
export CXXFLAGS+=" -ffat-lto-objects"

meson build \
    ${MESON_OPTIONS} \
    -D gles1=disabled \
    -D with-system-data-files=true

ninja -C build
ninja -C build install

install -m0755 build/src/egl/opengl/{eglgears_wayland,eglgears_x11,eglkms,egltri_wayland,egltri_x11,peglgears,xeglgears,xeglthreads} "$1"/usr/bin

