#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D admin_group=wheel \
    -D elogind=false \
    -D systemd=true \
    -D systemdsystemunitdir=/usr/lib/systemd/system \
    -D docbook=true \
    -D gtk_doc=true \
    -D user_heuristics=false

ninja -C build
ninja -C build install
