#!/bin/sh -uxe
export DESTDIR="$1"

patch -Np1 -i 0001-build-Properly-apply-modes-in-meson_post_install.py.patch

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D admin_group=wheel \
    -D docbook=true \
    -D gtk_doc=true 

ninja -C build
ninja -C build install
