#!/bin/sh -uxe

make full-ttf

install -Dt "$1/usr/share/fonts/TTF" -m644 build/*.ttf
install -Dt "$1"/usr/share/fontconfig/conf.avail -m644 fontconfig/*.conf

mkdir "$1"/usr/share/fontconfig/conf.default
ln -srt "$1"/usr/share/fontconfig/conf.default "$1"/usr/share/fontconfig/conf.avail/*
