#!/bin/sh -uxe
export DESTDIR="$1"

install -dm755 "$1"/{opt/multimc,usr/{bin,share/applications}}
mv MultiMC "$1"/opt/multimc/MultiMC
mv bin "$1"/opt/multimc/bin

ln -sf /opt/multimc/MultiMC "$1"/usr/bin/multimc

mv multimc.desktop "$1"/usr/share/applications
