#!/bin/sh -uxe

patch -Np1 -i libmpeg2-0.5.1-gcc4.6.patch

sed "/AC_PATH_XTRA/d" -i configure.ac

autoreconf -fiv

./configure \
    --prefix=/usr \
    --enable-shared \
    --disable-static

make \
    OPT_CFLAGS="$CFLAGS" \
    MPEG2DEC_CFLAGS="$CFLAGS" \
    LIBMPEG2_CFLAGS="$CFLAGS"

make DESTDIR="$1" install
