#!/bin/sh -e

export DESTDIR="$1"

cmake -B build -G Ninja \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=None 

ninja -C build
ninja -C build install

mkdir -p "$1/usr/lib/ccache/bin"

for link in \
    gcc     \
    g++     \
    c++     
do
    ln -s /usr/bin/ccache "$1/usr/lib/ccache/bin/$link"
    ln -s /usr/bin/ccache "$1/usr/lib/ccache/bin/${CHOST}-$link"
done

for link in \
    cc      \
    clang   \
    clang++
do
    ln -s /usr/bin/ccache "$1/usr/lib/ccache/bin/$link"
done
