#!/bin/sh -uxe

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --sbindir=/usr/bin \
    --with-rundir=/var/run \
    --libexecdir=/usr/lib/ConsoleKit \
    --localstatedir=/var \
    --enable-polkit \
    --enable-pam-module \
    --enable-udev-acl \
    --enable-docbook-docs \
    --with-dbus-services=/usr/share/dbus-1/services \
    --with-xinitrc-dir=/etc/X11/xinit/xinitrc.d \
    --with-pam-module-dir=/usr/lib/security \
    --without-systemdsystemunitdir 

make
make DESTDIR="$1" install
