#!/bin/sh -uxe
export DESTDIR="$1"

for i in *.patch; do
    patch -Np1 -i $i
done

meson build \
    ${MESON_OPTIONS} \
    -D gstreamer=disabled

ninja -C build
ninja -C build install

rm -rf "$1/usr/bin" "$1/etc"
