#!/bin/sh -uxe

mkdir build

# use system types
rm include/linux/types.h

# fix broken include
ln -rs libiptc/linux_list.h include/libiptc

# fix build with -Werror=format-security
patch -Np1 -i iptables-format-security.patch

cd build 

../configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib \
    --enable-bpf-compiler \
    --enable-devel \
    --enable-libipq \
    --enable-shared

sed -i "s| -shared | ${LDFLAGS}\0|g" libtool

make
make DESTDIR="$1" install
