#!/bin/sh -uxe

patch -p0 -i aclocal-fixes.patch

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info

make
make DESTDIR="$1" install

rm -f "$1"/usr/share/info/dir
