#!/bin/sh -uxe
export DESTDIR="$1"
export CFLAGS="${CFLAGS/-march=native/-march=x86-64-v3}"

cmake -B build -G Ninja \
    -D DESKTOP_APP_QT6=off \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_BUILD_TYPE=Release \
    -D TDESKTOP_API_ID=611335 \
    -D TDESKTOP_API_HASH=d524b414d21f4d37f08684c1df41ac9c

sed -i "s|rtp_utility.h|rtp_util.h|" Telegram/ThirdParty/tgcalls/tgcalls/MediaManager.cpp
ninja -C build 
ninja -C build install
