#!/bin/sh -uxe

# Fix https://github.com/madler/zlib/issues/613
patch -Np1 -i ec3df00224d4.patch

export CFLAGS+=" -flto=auto -ffat-lto-objects"
export CXXFLAGS+=" -flto=auto -ffat-lto-objects"

./configure \
	--prefix=/usr 

make 
make DESTDIR="$1" install

cd contrib/minizip
cp Makefile Makefile.orig

autoreconf -iv

./configure \
    --prefix=/usr \
    --enable-static=no
make 
make DESTDIR="$1" install

rm "$1"/usr/include/minizip/crypt.h
