#!/bin/sh -uxe

patch -p1 -i datadir.patch

sed -e "s/AM_CONFIG_HEADER(/AC_CONFIG_HEADERS(/" -i configure.ac
autoreconf -fiv

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --program-transform-name 's,docbook2,db2x_docbook2,'

make
make DESTDIR="$1" install

sed -i 's|http://docbook2x.sf.net/latest|/usr/share/docbook2X|g' \
    "$1"/usr/bin/db2x_xsltproc
