#!/bin/sh -uxe

patch -p1 -i datadir.patch

xslver="$(kiss l docbook-xsl | cut -d ' ' -f2 | cut -d '-' -f1)"

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --program-transform-name 's/docbook2/db2x_docbook2'

# Fix wrong docbook location.
sed -i "s|usr/share/xml/docbook/stylesheet|usr/share/xml/docbook/xsl-stylesheets-${2}|g" Makefile
make
make DESTDIR="$1" install
